Repository ldcumg/SnapRoad, pull requests merged in 2024-12, with the labels that each got.

#249 style: 디자인 qa 수정
  public/images/landing/02_landing.webp
  public/images/landing/03_landing.webp
  public/images/landing/04_landing.webp
  public/images/landing/05_landing.webp
  public/images/landing/06_landing.webp
  src/components/_common/ScrollReactHeader.tsx
  src/components/landing/ScrollSections.tsx
  src/stories/LinkButton.tsx
  src/stories/Modal.tsx
Labels: 스타일링

#250 style: 디자인 qa반영
  public/svgs/User_Group.svg
  src/components/groupList/GroupAddButton.tsx
  src/components/groupList/GroupItem.tsx
  src/components/groupList/RandomImage.tsx
  src/components/makegroup/ImagePreview.tsx
  src/services/server-action/getSignedImgUrl.ts
  src/stories/Button.tsx
  src/stories/DotSpinner.tsx
  src/stories/LengthInput.tsx
Labels: 스타일링

#251 fix: theme color 흰색으로 수정
  src/app/manifest.ts
Labels: 스타일링

#252 [Refactor] 디자인 qa 반영
  next.config.mjs
  src/components/map/GroupMap.tsx
  src/components/map/PostsPreviewLayout.tsx
  src/components/map/SearchResultLayout.tsx
  src/components/providers/QueryProvider.tsx
Labels: 기능 개발, 스타일링

#253 [QA] 로그인 페이지 디자인 QA
  src/components/auth/LoginForm.tsx
  src/components/auth/LoginHeader.tsx
  src/components/auth/LoginOptions.tsx
  src/components/auth/SocialLogin.tsx
  src/schemas/authSchemas.ts
  src/stories/Input.tsx
Labels: 리팩토링, 스타일링
