Repository ldcumg/SnapRoad, pull requests merged in 2024-11, with the labels that each got.

#48 [Style] 디자인시스템 폰트관련 config추가
  src/app/page.tsx
  src/services/server-action/groupServerActions.ts
  src/stories/Button.tsx
  tailwind.config.ts
Labels: 스타일링

#50 [Style] 그룹리스트 페이지 관련 스타일 작업
  next.config.mjs
  public/svgs/Arrow_Up_MD.svg
  public/svgs/Logo.svg
  public/svgs/Plus_LG.svg
  public/svgs/User.svg
  public/svgs/User_Group.svg
  public/svgs/cameraIcon.svg
  src/app/grouplist/layout.tsx
  src/app/grouplist/page.tsx
  src/app/makegroup/page.tsx
  src/components/_common/TopButton.tsx
  src/components/groupList/GroupAddButton.tsx
  src/components/groupList/GroupItem.tsx
  src/components/groupList/GroupList.tsx
  src/components/groupList/GroupListHeader.tsx
  src/components/groupList/RandomImage.tsx
  src/components/groupList/RandomImageSkeleton.tsx
  src/components/groupList/SubmitInviteForm.tsx
  src/components/providers/QueryProvider.tsx
  src/hooks/queries/byUse/useAuthQueries.ts
  src/hooks/queries/byUse/useGroupQueries.ts
  src/services/server-action/authActions.ts
  src/styles/globals.css
  src/types/groupTypes.ts
  src/types/userTypes.ts
  src/utils/dateUtils.ts
  src/utils/getSlicedAddress.ts
  tailwind.config.ts
Labels: 스타일링

#56 [Feat] storybook palette 클래스 네임 복사 기능
  src/app/guide/page.tsx
  src/components/groupList/RandomImage.tsx
  src/components/ui/colors.tsx
  src/components/ui/palettes.tsx
  src/stories/BottomSheet.stories.tsx
  src/stories/Button.stories.ts
  src/stories/Color.srories.ts
  src/stories/ColorChart.tsx
  src/stories/Palette.stories.tsx
  src/stories/Palette.tsx
  src/stories/Tab.stories.tsx
Labels: 스타일링

#52 [Feat] 그룹 앨범 거기에 지도와 그룹 정보를 곁들인
  .gitignore
  README.md
  next.config.mjs
  package.json
  pnpm-lock.yaml
  src/app/group/[groupId]/layout.tsx
  src/app/group/[groupId]/page.tsx
  src/components/groupDetail/GroupAlbum.tsx
  src/components/groupDetail/GroupMap.tsx
  src/components/groupDetail/MemberList.tsx
  src/hooks/queries/byUse/useGroupQueries.ts
  src/hooks/queries/post/useGroupPostsQuery.ts
  src/hooks/queries/queryKeys.ts
  src/services/server-action/groupServerActions.ts
  src/services/server-action/mapAction.ts
  src/services/server-action/postAction.ts
  src/types/groupTypes.ts
  src/types/placeTypes.ts
  src/types/postTypes.ts
  src/types/supabaseTypes.ts
Labels: 기능 개발

#57 [Style] 그룹리스트페이지 디자인 작업
  src/app/grouplist/page.tsx
  src/components/groupList/BlankGroupList.tsx
  src/components/groupList/GroupAddButton.tsx
  src/components/groupList/GroupList.tsx
  src/components/groupList/RandomImage.tsx
Labels: 스타일링

#59 [Add] MIT License 생성
  LICENSE
Labels: 구조 변경

#58 [Feat] 그룹 앨범 무한 스크롤
  package.json
  src/app/group/[groupId]/page.tsx
  src/components/groupDetail/GroupAlbum.tsx
  src/components/groupDetail/GroupMap.tsx
  src/components/groupDetail/MemberList.tsx
  src/hooks/queries/post/useGroupPostsQuery.ts
  src/services/server-action/postAction.ts
Labels: 기능 개발

#61 [Style] 스타일 관련 작업
  src/app/guide/page.tsx
  src/app/makegroup/layout.tsx
  src/components/_common/Spinner.tsx
  src/components/groupList/GroupAddButton.tsx
  src/components/groupList/GroupList.tsx
  src/components/groupList/RandomImage.tsx
  src/components/groupList/SubmitInviteForm.tsx
  src/components/makegroup/ImagePreview.tsx
  src/components/makegroup/MakeGroupForm.tsx
  src/components/makegroup/MakeGroupHeader.tsx
  src/components/ui/spinners.tsx
  src/hooks/queries/byUse/useGroupQueries.ts
  src/services/groupServices.ts
  src/stories/Button.tsx
  src/stories/Modal.tsx
  src/stories/Spinner.stories.tsx
  src/stories/Spinner.tsx
  src/styles/globals.css
  src/types/groupTypes.ts
  src/types/supabaseTypes.ts
  tailwind.config.ts
Labels: 기능 개발, 스타일링

#63 [Feat, Style] 게시물 이미지 마커, 마커 클릭 시 게시물 미리보기, 폴리라인 구현, 중심 좌표 장소 정보 불러오기, 아이콘 svg 적용
  public/svgs/Close_Member_List.svg
  public/svgs/Geolocation_btn.svg
  public/svgs/Group_Member.svg
  public/svgs/Map_Search.svg
  public/svgs/Mappin.svg
  public/svgs/Reset_input.svg
  public/svgs/Search_Result_Marker.svg
  public/svgs/Setting.svg
  public/svgs/Swap_Btn_To_Album.svg
  public/svgs/Swap_Btn_To_Map.svg
  public/svgs/Switch_btn_to_image_marker.svg
  public/svgs/Switch_btn_to_mappin_marker.svg
  public/svgs/Top_Btn.svg
  public/svgs/User_Plus.svg
  src/app/group/[groupId]/page.tsx
  src/components/groupDetail/GroupAlbum.tsx
  src/components/groupDetail/GroupMap.tsx
  src/components/groupDetail/GroupMapSearch.tsx
  src/components/groupDetail/MemberList.tsx
  src/constants/urls.ts
  src/hooks/queries/post/useGroupPostsQuery.ts
  src/services/server-action/mapAction.ts
  src/services/server-action/postAction.ts
  src/types/placeTypes.ts
  src/types/postTypes.ts
Labels: 기능 개발

#66 [Style] - 그룹관련 css작업
  public/images/group_default_thumbnail.png
  src/app/grouplist/page.tsx
  src/app/layout.tsx
  src/components/_common/Modal.tsx
  src/components/groupList/GroupAddButton.tsx
  src/components/groupList/GroupItem.tsx
  src/components/groupList/GroupItemSkeleton.tsx
  src/components/groupList/GroupList.tsx
  src/components/groupList/RandomImage.tsx
  src/components/groupList/SubmitInviteForm.tsx
  src/components/makegroup/InputSection.tsx
  src/components/makegroup/MakeGroupForm.tsx
  src/components/ui/modals.tsx
Labels: 스타일링

#68 [Style] 공통 LengthInput 생성
  src/components/makegroup/InputSection.tsx
  src/stories/LengthInput.tsx
Labels: 리팩토링, 스타일링

#69 [Refactor] queryKey 분리
  src/components/groupList/RandomImage.tsx
  src/hooks/queries/byUse/useGroupMutations.ts
  src/hooks/queries/byUse/useGroupQueries.ts
  src/hooks/queries/queryKeys.ts
Labels: 리팩토링

#75 [Move] ZustandProvider 파일 삭제
  src/components/providers/ZustandProvider.tsx
Labels: 구조 변경

#76 [Fix] button 잘못된 prop 수정
  src/stories/Header.tsx
Labels: 버그

#81 [Refactor] clusterCalculator 타입 지정
  .eslintrc.json
  src/app/group/[groupId]/page.tsx
  src/components/groupDetail/GroupMap.tsx
Labels: 리팩토링

#82 [Style] 랜딩페이지, 그룹리스트페이지 헤더 설정
  src/app/grouplist/layout.tsx
  src/app/grouplist/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/_common/ScrollReactHeader.tsx
  src/components/groupList/GroupAddButton.tsx
  src/components/groupList/GroupListHeader.tsx
  src/components/groupList/RandomImage.tsx
  src/components/layout/Header.tsx
  src/components/layout/LogoUserHeader.tsx
  src/hooks/queries/byUse/useProfileMutation.ts
  src/hooks/queries/byUse/useUserQuery.ts
  src/hooks/queries/queryKeys.ts
Labels: 기능 개발, 스타일링

#86 [Style] 캐러셀 데이터 없을 시 스타일 추가
  public/svgs/Empty_Marker.svg
  src/components/groupList/RandomImage.tsx
Labels: 스타일링

#91 [Fix] middleware redirect버그 수정
  src/hooks/queries/byUse/useAuthMutations.ts
  src/utils/supabase/middleware.ts
Labels: 버그

#89 [Doc]트러블 슈팅(정민지)
  README.md
Labels: 문서 수정

#92 [Fix] 캐러셀 스타일 디자인시안대로 수정
  src/components/groupList/RandomImage.tsx
Labels: 스타일링

#93 [Doc] README 수정
  README.md
Labels: 문서 수정

#84 [Style] 멤버리스트 스타일링
  src/app/group/[groupId]/page.tsx
  src/components/groupAlbum/MemberList.tsx
Labels: 스타일링

#96 [fix] 포스트 이동경로 수정
  src/components/groupList/RandomImage.tsx
Labels: 버그

#94 [Feat, Style] 그룹 초대코드 복사
  src/app/group/[groupId]/page.tsx
  src/components/groupAlbum/MemberList.tsx
  src/services/server-action/groupServerActions.ts
  src/services/server-action/postAction.ts
Labels: 기능 개발, 스타일링

#95 [Style] 지도 바텀시트 스타일링 적용
  public/svgs/Mappin.svg
  public/svgs/Marker.svg
  public/svgs/Plus_LG.svg
  src/app/group/[groupId]/page.tsx
  src/components/groupAlbum/GroupAlbum.tsx
  src/components/groupAlbum/MemberList.tsx
  src/components/map/GroupMap.tsx
  src/services/server-action/postAction.ts
  src/stories/BottomSheet.tsx
  src/types/mapTypes.ts
Labels: 스타일링

#100 [Hotfix] 미들웨어 로그인시 리다이렉트 로직 변경
  src/utils/supabase/middleware.ts
Labels: 긴급, 버그

#101 [Bugfix] 게시물 없을 때 지도 위치 재조정 로직 수정
  src/components/map/GroupMap.tsx
Labels: 버그

#106 [Hotfix] 카메라 아이콘 변경
  public/svgs/cameraIcon.svg
Labels: 스타일링

#107 [Fix] 그룹 앨범 게시물 없을 시 문구 표기
  src/app/group/[groupId]/page.tsx
  src/components/groupAlbum/GroupAlbum.tsx
  src/components/groupAlbum/GroupInfoBox.tsx
Labels: 구조 변경

#109 [Fix] 대표이미지에 위도, 경도 없을 시 지도 범위 재설정에서 제외
  src/app/group/[groupId]/page.tsx
  src/components/map/GroupMap.tsx
Labels: 버그

#112 [Feat] 선택한 위치의 주소가 없을 시 게시물 추가하기 버튼 비활성화
  src/components/map/GroupMap.tsx
  src/services/server-action/mapAction.ts
Labels: 기능 개발

#113 [Style] 그룹리스트페이지 이미지 최소크기 변경
  src/app/grouplist/page.tsx
  src/components/_common/TopButton.tsx
  src/components/groupList/GroupItem.tsx
Labels: 스타일링

#114 [Fix] 잘못된 커밋 복구
  src/components/map/GroupMap.tsx
Labels: 긴급, 버그

#117 [Update] 그룹 정보 수정 라우트 연결
  src/components/groupAlbum/GroupAlbum.tsx
  src/components/groupAlbum/GroupInfoBox.tsx
Labels: 기능 개발

#116 [Fix] 핀, 초기 위도 경도 조정
  src/components/map/GroupMap.tsx
Labels: 기능 개발

#118 [Style] 그룹생성페이지 로딩 시 스피너 화면에 보이도록 추가
  src/components/makegroup/MakeGroupForm.tsx
  src/hooks/queries/byUse/useGroupMutations.ts
  src/hooks/queries/byUse/useGroupQueries.ts
  src/stories/Spinner.tsx
Labels: 기능 개발, 스타일링

#119 [Feat] 그룹 리스트 버튼 스타일 변경 및 그룹생성 disabled 유효성검사 추가
  src/components/groupList/GroupAddButton.tsx
  src/components/makegroup/MakeGroupForm.tsx
  src/hooks/byUse/useGroupForm.ts
Labels: 기능 개발, 스타일링

#120 [Feat] loading notfound 페이지 생성
  public/svgs/Not_Found_Marker.svg
  src/app/loading.tsx
  src/app/not-found.tsx
  src/components/_common/DotSpinner.tsx
  tailwind.config.ts
Labels: 기능 개발, 스타일링

#130 [Bugfix, Style] 맵핀 상태에서 헤더 버튼 미활성 해결, 검색 결과 더보기 버튼
  public/svgs/Reload.svg
  src/app/group/[groupId]/page.tsx
  src/components/map/GroupMap.tsx
  src/stories/BottomSheet.tsx
  src/stories/Button.tsx
Labels: 스타일링, 버그

#131 [Refactor] 그룹 상세페이지 zustand 적용 및 마우스 호버 프리페치 적용
  src/app/group/[groupId]/page.tsx
  src/app/layout.tsx
  src/components/groupAlbum/GroupAlbum.tsx
  src/components/groupAlbum/GroupInfoBox.tsx
  src/components/providers/GroupDetailModeProvider.tsx
  src/hooks/groupDetail/useGroupDetailModeStore.ts
  src/hooks/queries/post/useGroupPostsQuery.ts
  src/stores/groupDetail/groupDetailStore.ts
  src/types/groupTypes.ts
Labels: 리팩토링

#132 [Refactor] 게시물 마커 prefetch
  src/app/group/[groupId]/layout.tsx
Labels: 리팩토링

#136 [Refactor] landingpage 피드백 리팩토링
  src/app/grouplist/layout.tsx
  src/app/page.tsx
  src/components/landing/ScrollSections.tsx
  src/components/layout/LogoUserHeader.tsx
  src/constants/urls.ts
  src/utils/supabase/middleware.ts
Labels: 리팩토링

#139 [Feat] 그룹 이미지 crop 기능 추가
  package.json
  pnpm-lock.yaml
  src/components/_common/ImageCropper.tsx
  src/components/groupList/GroupItem.tsx
  src/components/makegroup/InputSection.tsx
  src/components/makegroup/MakeGroupForm.tsx
  src/hooks/byUse/useGroupForm.ts
  src/schemas/groupSchemas.ts
  src/types/CropTypes.ts
  src/utils/getCroppedImage.ts
Labels: 기능 개발

#141 refac : 상세 이미지 캐러셀 샤드시엔 사용
  src/components/post/postDetail/PostDetailCarousel.tsx
  src/components/post/postDetail/PostDetailDesc.tsx
  src/components/post/postDetail/PostDetailHeader.tsx
  src/components/post/postDetail/PostImages.tsx
  src/styles/postDetail.css
Labels: 리팩토링

#145 [Refactor] metadata 설정, ogtag 설정
  public/images/ogImage/og_image.jpg
  src/app/favicon.ico
  src/app/grouplist/layout.tsx
  src/app/grouplist/page.tsx
  src/app/layout.tsx
  src/app/makegroup/layout.tsx
Labels: 리팩토링

#147 [Update] signed url 적용
  public/svgs/Geolocation_btn.svg
  public/svgs/Mappin.svg
  public/svgs/Marker.svg
  public/svgs/Search_Result_Marker.svg
  public/svgs/Switch_btn_to_image_marker.svg
  public/svgs/Switch_btn_to_mappin_marker.svg
  src/app/group/[groupId]/page.tsx
  src/components/groupAlbum/GroupAlbum.tsx
  src/components/groupAlbum/GroupInfoBox.tsx
  src/components/groupAlbum/MemberList.tsx
  src/components/groupList/GroupList.tsx
  src/components/groupList/RandomImage.tsx
  src/components/makegroup/MakeGroupForm.tsx
  src/components/map/GroupMap.tsx
  src/constants/buckets.ts
  src/constants/time.ts
  src/constants/urls.ts
  src/hooks/queries/group/useGroupQueries.ts
  src/hooks/queries/post/useGroupPostsQuery.ts
  src/hooks/queries/queryKeys.ts
  src/services/server-action/groupServerActions.ts
  src/services/server-action/postAction.ts
  src/styles/globals.css
Labels: 기능 개발

#152 [Refactor] 마우스 훠벌 프리패치를 서버 프리패치로 변경
  src/app/group/[groupId]/layout.tsx
  src/app/group/[groupId]/page.tsx
  src/components/groupAlbum/GroupAlbum.tsx
  src/hooks/queries/post/useGroupPostsQuery.ts
  src/services/server-action/postAction.ts
Labels: 리팩토링

#154 [Fix] middleware Privateurls 관련 수정
  src/constants/urls.ts
Labels: 버그

#155 [Fix] middlware privateurls 관련 타입 에러
  src/constants/urls.ts
  src/utils/supabase/middleware.ts
Labels: 버그

#150 [Feat] 지도 키워드 검색
  src/app/group/[groupId]/page.tsx
  src/components/map/GroupMap.tsx
  src/components/map/PlaceSearchForm.tsx
  src/services/server-action/groupServerActions.ts
  src/services/server-action/postAction.ts
  src/styles/globals.css
Labels: 기능 개발

#153 [Feat] 위도 경도 받아와서 보여주기
  src/app/group/[groupId]/page.tsx
  src/components/map/GroupMap.tsx
Labels: 기능 개발

#159 [Hotfix] 게시물 추가하기 버튼
  src/app/group/[groupId]/page.tsx
  src/components/map/GroupMap.tsx
Labels: 긴급

#161 [Fix] ogImage 설정 변경
  src/app/layout.tsx
Labels: 버그

#162 [Style] 장소 정보 바텀시트 스타일
  src/components/map/GroupMap.tsx
Labels: 스타일링

#163 [Style] 지도 svg
  public/svgs/Geolocation_btn.svg
  public/svgs/Switch_btn_to_image_marker.svg
  public/svgs/Switch_btn_to_mappin_marker.svg
  src/components/map/GroupMap.tsx
Labels: 스타일링

#168 [Refactor] 그룹 이름 placeholder추가
  src/components/makegroup/InputSection.tsx
Labels: 리팩토링

#169 [Hotfix] 바텀 시트 닫기 버튼 적용
  src/app/sentry-example-page/page.tsx
  src/components/map/GroupMap.tsx
  src/lib/icon/Close_Lg.tsx
Labels: 기능 개발

#170 [Hotfix] 클러스터 마커에 바텀시트 이벤트 적용
  src/components/map/GroupMap.tsx
  src/stories/BottomSheet.tsx
Labels: 기능 개발

#173 [Update] post_id가 null인 데이터 필터링
  src/services/server-action/postAction.ts
Labels: 기능 개발

#178 [Refactor] 그룹리스트 페이지 prefetch 적용, 그룹리스트가 없으면 randompost안나타나도록
  src/app/grouplist/layout.tsx
  src/components/groupList/RandomImage.tsx
  src/components/layout/LogoUserHeader.tsx
Labels: 리팩토링

#184 [Refactor] topbutton 스크롤 내리면 생기도록 디바운스 이벤트 처리
  src/stories/TopButton.tsx
  src/utils/debounce.ts
Labels: 리팩토링

#188 [Style] grouplist 페이지 pc 반응형 추가
  public/images/group_default_thumbnail.png
  src/app/grouplist/layout.tsx
  src/app/grouplist/page.tsx
  src/app/layout.tsx
  src/components/_common/ScrollReactHeader.tsx
  src/components/groupList/GroupAddButton.tsx
  src/components/groupList/GroupList.tsx
  src/components/groupList/RandomImage.tsx
  src/components/makegroup/MakeGroupForm.tsx
  src/components/ui/carousel.tsx
  src/hooks/byUse/useMediaQuery.ts
  src/lib/icon/Icon_Arrow_Back_LG.tsx
  src/lib/icon/Icon_Arrow_Forward_LG.tsx
  src/lib/styles/globals.css
  src/stories/Modal.tsx
  tailwind.config.ts
Labels: 기능 개발, 리팩토링, 스타일링

#189 [Refactor] 불필요 코드 삭제, prefetch query, promise.all
  public/images/group_default_thumbnail.jpg
  src/app/grouplist/layout.tsx
  src/components/makegroup/InputSection.tsx
  src/components/makegroup/MakeGroupForm.tsx
  src/hooks/queries/byUse/useGroupMutations.ts
  src/hooks/queries/group/useGroupQueries.ts
  src/schemas/groupSchemas.ts
  src/services/client-action/groupActions.ts
Labels: 기능 개발, 리팩토링

#190 [Style] grouplist 반응형 작업
  src/components/groupList/GroupAddButton.tsx
  src/components/groupList/SubmitInviteForm.tsx
Labels: 리팩토링, 스타일링

#180 [Fix, Update] 기본 마커 보더 적용, 사용자 위치 찾기 시 위치 정보 불러오기
  src/app/group/[groupId]/layout.tsx
  src/app/group/[groupId]/page.tsx
  src/app/layout.tsx
  src/components/groupAlbum/GroupAlbum.tsx
  src/components/groupAlbum/GroupInfoBox.tsx
  src/components/map/GroupMap.tsx
  src/components/providers/GroupDetailModeProvider.tsx
  src/components/providers/PostPositioningProvider.tsx
  src/hooks/ zustandContext/usePostPositioningStore.ts
  src/hooks/groupDetail/useGroupDetailModeStore.ts
  src/hooks/queries/post/useFormMutations.ts
  src/hooks/queries/post/useGroupPostsQuery.ts
  src/hooks/queries/queryKeys.ts
  src/lib/icon/Search_Result_Marker.tsx
  src/lib/styles/globals.css
  src/stores/groupDetail/groupDetailStore.ts
  src/stores/post/postPositioningStore.ts
  src/types/groupTypes.ts
  src/types/postTypes.ts
Labels: 기능 개발, 리팩토링, 스타일링

#191 [Style] 머지 미반영부분 수정
  src/app/layout.tsx
  src/components/groupAlbum/GroupInfoBox.tsx
  src/components/groupList/SubmitInviteForm.tsx
  src/components/makegroup/ImagePreview.tsx
Labels: 스타일링

#192 [Style] 그룹리스트 반응형 작업
  src/components/groupList/GroupItem.tsx
  src/components/groupList/GroupList.tsx
  src/components/groupList/RandomImage.tsx
Labels: 스타일링

#193 [Style] 그룹 수정 반응형 디자인
  src/components/groupAlbum/GroupAlbum.tsx
  src/components/groupAlbum/GroupInfoBox.tsx
  src/components/makegroup/MakeGroupForm.tsx
  src/hooks/queries/byUse/useGroupMutations.ts
  src/stories/Modal.tsx
Labels: 스타일링

#195 refactor] 랜딩페이지 최적화 작업
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/images/landing/01_landing.jpg
  public/images/landing/01_landing.webp
  public/images/landing/02_landing.jpg
  public/images/landing/02_landing.webp
  public/images/landing/03_landing.jpg
  public/images/landing/03_landing.webp
  public/images/landing/04_landing.jpg
  public/images/landing/04_landing.webp
  public/images/landing/05_landing.jpg
  public/images/landing/05_landing.webp
  public/images/landing/06_landing.jpg
  public/images/landing/06_landing.webp
  src/components/landing/ScrollSections.tsx
  src/services/server-action/groupServerActions.ts
Labels: 리팩토링

#198 [Refactor] preview 렌더링용 그룹 기본 이미지 생성 및 사용
  public/images/group_default_thumbnail.webp
  src/components/makegroup/ImagePreview.tsx
Labels: 리팩토링

#199 [Feat] 수정 페이지 이미지 제외 적용 완료
  package.json
  pnpm-lock.yaml
  src/app/group/[groupId]/post/[postId]/edit/page.tsx
  src/components/post/EditForms.tsx
  src/components/post/PostForms.tsx
  src/components/post/postDetail/OptionsMenu.tsx
  src/components/ui/DateInputWithIcon.tsx
  src/components/ui/TimeInputWithIcon.tsx
  src/hooks/byUse/usePostForm.ts
  src/hooks/queries/post/ConvertTo24HourFormat.ts
  src/hooks/queries/post/useFormMutations.ts
  src/schemas/formSchemas.ts
  src/stories/BottomSheet.tsx
Labels: 기능 개발, 리팩토링

#200 [Fix] route.push -> route.replace
  package.json
  pnpm-lock.yaml
  src/app/group/[groupId]/layout.tsx
  src/app/group/[groupId]/page.tsx
  src/components/map/GroupMap.tsx
  src/components/toast/GarlicToast.tsx
  src/services/server-action/groupServerActions.ts
  src/services/server-action/postAction.ts
  src/types/postTypes.ts
Labels: 긴급

#201 [Fix] 지도 바텀시트
  src/components/map/GroupMap.tsx
  src/components/myPage/AccountSetting.tsx
  src/components/ui/myForm.tsx
Labels: 긴급

#202 [Refactor] 디자인 qa 적용
  src/components/_common/ImageCropper.tsx
  src/components/groupList/GroupAddButton.tsx
  src/components/layout/LogoUserHeader.tsx
  src/components/makegroup/MakeGroupForm.tsx
  src/hooks/queries/byUse/useGroupMutations.ts
Labels: 리팩토링, 스타일링

#204 [Fix] 해시태그 중첩되는 요소 삭제 및 delete 정책 추가
  src/components/post/EditForms.tsx
  src/services/server-action/formActions.ts
Labels: 기능 개발, 리팩토링

#205 [Refactor] postForm PC 레이아웃 부분만 완성(form 태그에서 발생한 SSR 및 Hydration 오류 해결)
  src/app/group/[groupId]/post/[postId]/edit/page.tsx
  src/app/group/[groupId]/post/page.tsx
  src/components/_common/ScrollReactHeader.tsx
  src/components/layout/LayoutMain.tsx
  src/components/post/PostAddress.tsx
  src/components/post/PostForms.tsx
  src/components/post/PostPageClient.tsx
  src/hooks/byUse/useMediaQuery.ts
Labels: 리팩토링, 스타일링

#207 [Refactor] customform 폴더 변경
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/groupList/SubmitInviteForm.tsx
  src/components/makegroup/MakeGroupForm.tsx
  src/components/myPage/PasswordResetForm.tsx
  src/components/myPage/PasswordResetInfo.tsx
  src/components/myPage/ProfileUpdate.tsx
  src/components/post/EditForms.tsx
  src/components/post/PostForms.tsx
  src/components/post/postDetail/CommentForm.tsx
  src/components/post/postDetail/CommentUpdateForm.tsx
  src/components/ui/myForm.tsx
  src/hooks/useCustomForm/useAuthForm.ts
  src/hooks/useCustomForm/useCommentForm.ts
  src/hooks/useCustomForm/useGroupForm.ts
  src/hooks/useCustomForm/useImageUploadForm.ts
  src/hooks/useCustomForm/usePostForm.ts
  src/hooks/useCustomForm/useProfileForm.ts
Labels: 리팩토링, 구조 변경

#210 [Refactor] group action 관련 불필요 코드 삭제
  src/services/client-action/groupActions.ts
  src/services/server-action/groupServerActions.ts
Labels: 리팩토링

#211 [Refactor] 페이지 접근성 향상을 위한 aria-label적용
  src/app/grouplist/layout.tsx
  src/components/groupList/SubmitInviteForm.tsx
  src/components/layout/LogoUserHeader.tsx
Labels: 리팩토링

#212 [Refactor] group_image_url이 없을 경우 signed url 요청 로직이 실행되지 않게 변경
  src/constants/tables.ts
  src/services/groupServices.ts
  src/services/postDetailService.ts
  src/services/postService.ts
  src/services/server-action/authActions.ts
  src/services/server-action/commentAction.ts
  src/services/server-action/formActions.ts
  src/services/server-action/groupServerActions.ts
  src/services/server-action/postAction.ts
  src/services/server-action/postFormAction.ts
  src/services/server-action/profilesAction.ts
Labels: 리팩토링

#214 refactor: 버튼 반응형 스타일 추가, 피드백반영
  src/components/groupList/RandomImage.tsx
  src/stories/Button.tsx
  src/stories/LinkButton.tsx
  tailwind.config.ts
Labels: 스타일링

#218 [Style] 그룹 상세 페이지 pc버전
  .github/PULL_REQUEST_TEMPLATE.md
  src/app/group/[groupId]/layout.tsx
  src/app/group/[groupId]/page.tsx
  src/components/groupDetail/GroupAlbum.tsx
  src/components/groupDetail/GroupDetailHeader.tsx
  src/components/groupDetail/GroupInfoBox.tsx
  src/components/groupDetail/MemberList.tsx
  src/components/map/GroupMap.tsx
  src/components/map/PlaceSearchForm.tsx
  src/components/map/PostsPreviewLayout.tsx
  src/components/map/SearchResultLayout.tsx
Labels: 스타일링

#220 [Style] 디자인 Q/A 반영
  src/components/map/GroupMap.tsx
  src/components/map/SearchResultLayout.tsx
  src/stories/BottomSheet.tsx
Labels: 스타일링

#221 [Style] 반응형 작업 중 실수한 부분 수정
  src/components/map/GroupMap.tsx
Labels: 스타일링

#237 add: 삭제된 svg 재생성
  public/svgs/Plus_LG.svg
  src/components/groupList/GroupAddButton.tsx
Labels: 스타일링

#238 refactor: +버튼 색상변경
  public/svgs/Plus_LG.svg
Labels: 스타일링

#241 [Refactor] 지도에 사용하는 함수 customhook으로 분리
  src/components/map/GroupMap.tsx
  src/hooks/map/useKakaoMap.ts
  src/types/mapTypes.ts
Labels: 리팩토링

#242 [Fix] 위치 미지정 시 게시물 추가 버튼 숨기기
  src/components/map/GroupMap.tsx
  src/hooks/map/useKakaoMap.ts
Labels: 긴급

#244 [Fix] 로직 분리 중 놓친 부분 수정
  src/components/map/GroupMap.tsx
Labels: 긴급, 버그

#246 [Fix] 게시물 위치정보 없을 때 폴리라인 대응
  src/components/map/GroupMap.tsx
Labels: 긴급

#247 [Hotfix] 위치정보 없을 때 폴리라인 대응
  src/components/map/GroupMap.tsx
Labels: 긴급
