Repository ldcumg/SnapRoad, pull requests merged in 2024-10, with the labels that each got.

#4 [Docs] 이슈 템플릿 라벨 연결 및 PR 템플릿 수정
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/feature-request-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/hooks/queries/QueryProvider.tsx
Labels: 문서 수정

#5 [Fix] - Provider 경로 수정
  src/app/layout.tsx
  src/hooks/queries/QueryProvider.tsx
Labels: 구조 변경

#9 [feat] 그룹 생성 기능 추가
  package.json
  pnpm-lock.yaml
  src/app/auth/callback/route.ts
  src/app/groupdetail/page.tsx
  src/app/makegroup/error.tsx
  src/app/makegroup/page.tsx
  src/hooks/byUse/useGroupForm.ts
  src/hooks/queries/byUse/useGroupMutations.ts
  src/schemas/groupSchemas.ts
  src/services/client-action/groupActions.ts
  src/services/groupServices.ts
  src/types/groupTypes.ts
  src/utils/supabase/client.ts
Labels: 기능 개발

#11 [Feat] : 이메일 회원가입
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/auth/SignUpForm.tsx
  src/constants/authMessage.ts
  src/constants/urls.ts
  src/hooks/byUse/useAuthForm.ts
  src/hooks/queries/byUse/useAuthMutations.ts
  src/schemas/authSchemas.ts
  src/services/server-action/authActions.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Header.tsx
  src/stories/Input.tsx
Labels: 기능 개발

#15 [Feat] 그룹 생성 시 그룹이미지 추가
  public/images/.gitkeep
  public/images/group_default_thumbnail.png
  src/app/makegroup/page.tsx
  src/hooks/byUse/useGroupForm.ts
  src/hooks/queries/byUse/useGroupMutations.ts
  src/schemas/groupSchemas.ts
  src/services/client-action/groupActions.ts
Labels: 기능 개발

#18 [Feat] 초대 수락페이지 수락/그룹정보 기능 추가
  src/app/acceptinvite/error.tsx
  src/app/acceptinvite/page.tsx
  src/hooks/byUse/.gitkeep
  src/hooks/queries/byUse/.gitkeep
  src/hooks/queries/byUse/useGroupMutations.ts
  src/hooks/queries/byUse/useGroupQueries.ts
  src/services/client-action/groupActions.ts
  src/services/server-action/groupServerActions.ts
Labels: 기능 개발

#23 feat: 그룹 리스트 페이지 무한스크롤 추가
  src/app/grouplist/layout.tsx
  src/app/grouplist/page.tsx
  src/components/groupList/GroupItem.tsx
  src/components/groupList/GroupItemSkeleton.tsx
  src/components/groupList/GroupList.tsx
  src/components/groupList/GroupListHeader.tsx
  src/components/groupList/RandomImage.tsx
  src/hooks/byUse/useIntersection.ts
  src/hooks/queries/byUse/useGroupQueries.ts
  src/services/client-action/groupActions.ts
  src/services/groupServices.ts
  src/services/server-action/getSignedImgUrl.ts
  src/services/server-action/groupServerActions.ts
Labels: 기능 개발

#27 [Feat] 그룹 리스트페이지 랜덤이미지 및 그룹 리스트 무한스크롤 기능 추가
  src/app/grouplist/page.tsx
  src/components/groupList/RandomImage.tsx
  src/services/server-action/groupServerActions.ts
  src/utils/getRandomElement.ts
Labels: 기능 개발

#29 [Refactor] 그룹 리스트 기능 중 유저 카운트관련 로직 rpc사용하여 최적화
  src/app/grouplist/page.tsx
  src/components/groupList/GroupItem.tsx
  src/components/groupList/GroupList.tsx
  src/components/groupList/RandomImage.tsx
  src/hooks/queries/byUse/useGroupQueries.ts
  src/services/groupServices.ts
  src/services/server-action/getSignedImgUrls.ts
  src/types/groupTypes.ts
Labels: 리팩토링

#33 [Feat] 그룹 정보 수정 기능 추가
  public/svgs/cameraIcon.svg
  src/app/makegroup/page.tsx
  src/hooks/queries/byUse/useGroupMutations.ts
  src/hooks/queries/byUse/useGroupQueries.ts
  src/schemas/groupSchemas.ts
  src/services/client-action/groupActions.ts
  src/services/groupServices.ts
  src/services/server-action/groupServerActions.ts
  src/types/groupTypes.ts
Labels: 기능 개발

#37 [Refactor] 그룹 생성 및 업데이트 페이지 컴포넌트 분리 및 업데이트 상태시 초기 로딩 추가
  src/app/makegroup/page.tsx
  src/components/_common/Spinner.tsx
  src/components/makegroup/ImagePreview.tsx
  src/components/makegroup/InputSection.tsx
  src/components/makegroup/MakeGroupForm.tsx
Labels: 기능 개발

#45 [Feat] 랜덤 포스트 캐러셀 + 머지
  package.json
  pnpm-lock.yaml
  public/svgs/Close.svg
  public/svgs/Logo.svg
  src/app/grouplist/page.tsx
  src/components/_common/Modal.tsx
  src/components/groupList/GroupAddButton.tsx
  src/components/groupList/RandomImage.tsx
  src/components/groupList/SubmitInviteForm.tsx
  src/components/layout/Nav.tsx
  src/hooks/queries/byUse/useGroupQueries.ts
  src/styles/globals.css
Labels: 기능 개발

#46 [hotfix] 그룹 생성 폼 관련 타입에러 제거 및 shadcn 캐러셀,카드 추가
  src/components/makegroup/MakeGroupForm.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/carousel.tsx
Labels: 긴급, 버그

#47 [Fix, Feat] 장소 선택 방식 변경, 검색 결과 더보기
  next.config.mjs
  npm.js
  package.json
  pnpm-lock.yaml
  pnpm.txt
  src/app/group/[groupId]/page.tsx
  src/components/groupDetail/GroupMap copy.tsx
  src/components/groupDetail/GroupMap.tsx
  src/components/markerTracker/Marker.tsx
  src/components/markerTracker/TooltipMarker.tsx
  src/components/markerTracker/Tracker.tsx
  src/services/server-action/mapAction.ts
  src/styles/globals.css
  src/types/placesTypes.ts
Labels: 기능 개발, 구조 변경
